export declare const rangoOnChainTradeTypes: {
    readonly "10K_SWAP": "10KSwap";
    readonly PANGOLIN: "Pangolin Swap";
    readonly SUSHI_SWAP: "Sushi Swap";
    readonly OSMOSIS_SWAP: "Osmosis";
    readonly UNISWAP_V2: "UniSwapV2";
    readonly VVS_FINANCE: "VVS Finance";
    readonly MM_FINANCE: "MM Finance";
    readonly CRONA_SWAP: "Crona Swap";
    readonly OOLONG_SWAP: "Oolong Swap";
    readonly TRISOLARIS: "Trisolaris Swap";
    readonly MOJITO_SWAP: "Mojito Swap";
    readonly NET_SWAP: "Netswap";
    readonly VOLTAGE_SWAP: "Voltage Swap";
    readonly PANCAKE_SWAP: "PancakeV2";
    readonly PANCAKE_SWAP_V3: "PancakeV3";
    readonly UNI_SWAP_V3: "UniSwapV3";
    readonly KYBER_SWAP: "KyberSwapV3";
    readonly JUPITER: "Jupiter";
    readonly OPEN_OCEAN: "Open Ocean";
    readonly CURVE: "CurveFi";
    readonly QUICK_SWAP: "Quick Swap";
    readonly XY_DEX: "XY Finance";
    readonly SOLAR_BEAM: "Solarbeam";
    readonly AURORA_SWAP: "Aurora Swap";
    readonly STELLA_SWAP: "Stella Swap";
    readonly ONE_INCH: "1Inch";
    readonly BEAM_SWAP: "Beam Swap";
    readonly PARA_SWAP: "ParaSwap";
    readonly SYNAPSE: "Synapse Swapper";
    readonly FINKUJIRA: "Fin Kujira";
    readonly SOLANA: "Solana Wrapper";
    readonly AVNU: "Avnu";
    readonly ECHO_DEX: "EchoDEX";
    readonly SPACEFI_SWAP: "SpaceFi";
    readonly WYND: "Wynd Dex";
    readonly SUN_SWAP: "Sun Swap";
    readonly MDEX: "MDex";
    readonly OKC_SWAP: "Okc Swap";
    readonly CHERRY_SWAP: "Cherry Swap";
};
export declare const rangoCrossChainTradeTypes: {
    readonly across: "Across";
    readonly voyager: "Voyager";
    readonly cbridge: "CBridge";
    readonly rainbow: "Rainbow Bridge";
    readonly synapse: "Synapse Bridge";
    readonly optimism: "Optimism Bridge";
    readonly orbiter_bridge: "Orbiter";
    readonly mayaprotocol: "Maya Protocol";
    readonly xy: "XY Finance";
    readonly thorchain: "ThorChain";
    readonly arbitrum: "Arbitrum Bridge";
    readonly allbridge: "AllBridge";
    readonly hyphen: "Hyphen";
    readonly celercircle: "Circle";
    readonly ibc: "IBC";
    readonly stargate: "Stargate";
    readonly satellite: "Satellite";
    readonly symbiosis: "Symbiosis";
    readonly osmosis: "Osmosis";
};
export declare const rangoTradeTypes: {
    readonly across: "Across";
    readonly voyager: "Voyager";
    readonly cbridge: "CBridge";
    readonly rainbow: "Rainbow Bridge";
    readonly synapse: "Synapse Bridge";
    readonly optimism: "Optimism Bridge";
    readonly orbiter_bridge: "Orbiter";
    readonly mayaprotocol: "Maya Protocol";
    readonly xy: "XY Finance";
    readonly thorchain: "ThorChain";
    readonly arbitrum: "Arbitrum Bridge";
    readonly allbridge: "AllBridge";
    readonly hyphen: "Hyphen";
    readonly celercircle: "Circle";
    readonly ibc: "IBC";
    readonly stargate: "Stargate";
    readonly satellite: "Satellite";
    readonly symbiosis: "Symbiosis";
    readonly osmosis: "Osmosis";
    readonly "10K_SWAP": "10KSwap";
    readonly PANGOLIN: "Pangolin Swap";
    readonly SUSHI_SWAP: "Sushi Swap";
    readonly OSMOSIS_SWAP: "Osmosis";
    readonly UNISWAP_V2: "UniSwapV2";
    readonly VVS_FINANCE: "VVS Finance";
    readonly MM_FINANCE: "MM Finance";
    readonly CRONA_SWAP: "Crona Swap";
    readonly OOLONG_SWAP: "Oolong Swap";
    readonly TRISOLARIS: "Trisolaris Swap";
    readonly MOJITO_SWAP: "Mojito Swap";
    readonly NET_SWAP: "Netswap";
    readonly VOLTAGE_SWAP: "Voltage Swap";
    readonly PANCAKE_SWAP: "PancakeV2";
    readonly PANCAKE_SWAP_V3: "PancakeV3";
    readonly UNI_SWAP_V3: "UniSwapV3";
    readonly KYBER_SWAP: "KyberSwapV3";
    readonly JUPITER: "Jupiter";
    readonly OPEN_OCEAN: "Open Ocean";
    readonly CURVE: "CurveFi";
    readonly QUICK_SWAP: "Quick Swap";
    readonly XY_DEX: "XY Finance";
    readonly SOLAR_BEAM: "Solarbeam";
    readonly AURORA_SWAP: "Aurora Swap";
    readonly STELLA_SWAP: "Stella Swap";
    readonly ONE_INCH: "1Inch";
    readonly BEAM_SWAP: "Beam Swap";
    readonly PARA_SWAP: "ParaSwap";
    readonly SYNAPSE: "Synapse Swapper";
    readonly FINKUJIRA: "Fin Kujira";
    readonly SOLANA: "Solana Wrapper";
    readonly AVNU: "Avnu";
    readonly ECHO_DEX: "EchoDEX";
    readonly SPACEFI_SWAP: "SpaceFi";
    readonly WYND: "Wynd Dex";
    readonly SUN_SWAP: "Sun Swap";
    readonly MDEX: "MDex";
    readonly OKC_SWAP: "Okc Swap";
    readonly CHERRY_SWAP: "Cherry Swap";
};
export type RubicOnChainTradeTypeForRango = keyof typeof rangoOnChainTradeTypes;
export type RubicTradeTypeForRango = keyof typeof rangoTradeTypes;
export type RangoTradeType = (typeof rangoTradeTypes)[keyof typeof rangoTradeTypes];
