import { XyDexArbitrumProvider } from "../../providers/dexes/arbitrum/xy-dex-arbitrum/xy-dex-arbitrum-provider";
import { XyDexAvalancheProvider } from "../../providers/dexes/avalanche/xy-dex-avalanche/xy-dex-avalanche-provider";
import { XyDexBaseProvider } from "../../providers/dexes/base/xy-dex-base/xy-dex-base-provider";
import { XyDexBscProvider } from "../../providers/dexes/bsc/xy-dex-bsc/xy-dex-bsc-provider";
import { XyDexEthereumProvider } from "../../providers/dexes/ethereum/xy-dex-ethereum/xy-dex-ethereum-provider";
import { XyDexFantomProvider } from "../../providers/dexes/fantom/xy-dex-fantom/xy-dex-fantom-provider";
import { XyDexLineaProvider } from "../../providers/dexes/linea/xy-dex-linea/xy-dex-linea-provider";
import { XyDexMantleProvider } from "../../providers/dexes/mantle/xy-dex-mantle/xy-dex-mantle-provider";
import { XyDexMoonriverProvider } from "../../providers/dexes/moonriver/xy-dex-moonriver/xy-dex-moonriver-provider";
import { XyDexOptimismProvider } from "../../providers/dexes/optimism/xy-dex-optimism/xy-dex-optimism-provider";
import { XyDexPolygonProvider } from "../../providers/dexes/polygon/xy-dex-polygon/xy-dex-polygon-provider";
import { XyDexZkevmProvider } from "../../providers/dexes/polygon-zkevm/xy-dex-zkevm/xy-dex-zkevm-provider";
import { XyDexScrollProvider } from "../../providers/dexes/scroll/xy-dex-scroll/xy-dex-scroll-provider";
import { XyDexZksyncProvider } from "../../providers/dexes/zksync/xy-dex-zksync/xy-dex-zksync-provider";
export declare const xyDexTradeProviders: (typeof XyDexBscProvider | typeof XyDexEthereumProvider | typeof XyDexPolygonProvider | typeof XyDexFantomProvider | typeof XyDexAvalancheProvider | typeof XyDexArbitrumProvider | typeof XyDexOptimismProvider | typeof XyDexMoonriverProvider | typeof XyDexZksyncProvider | typeof XyDexZkevmProvider | typeof XyDexLineaProvider | typeof XyDexBaseProvider | typeof XyDexScrollProvider | typeof XyDexMantleProvider)[];
