"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.blockchainId = void 0;
const blockchain_name_1 = require("../../../models/blockchain-name");
const otherChains = Object.values(blockchain_name_1.BLOCKCHAIN_NAME).reduce((acc, blockchain) => ({ ...acc, [blockchain]: NaN }), {});
exports.blockchainId = {
    ...otherChains,
    // EVN blockchains
    [blockchain_name_1.BLOCKCHAIN_NAME.ETHEREUM]: 1,
    [blockchain_name_1.BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: 56,
    [blockchain_name_1.BLOCKCHAIN_NAME.POLYGON]: 137,
    [blockchain_name_1.BLOCKCHAIN_NAME.POLYGON_ZKEVM]: 1101,
    [blockchain_name_1.BLOCKCHAIN_NAME.AVALANCHE]: 43114,
    [blockchain_name_1.BLOCKCHAIN_NAME.MOONRIVER]: 1285,
    [blockchain_name_1.BLOCKCHAIN_NAME.FANTOM]: 250,
    [blockchain_name_1.BLOCKCHAIN_NAME.HARMONY]: 1666600000,
    [blockchain_name_1.BLOCKCHAIN_NAME.ARBITRUM]: 42161,
    [blockchain_name_1.BLOCKCHAIN_NAME.AURORA]: 1313161554,
    [blockchain_name_1.BLOCKCHAIN_NAME.TELOS]: 40,
    [blockchain_name_1.BLOCKCHAIN_NAME.OPTIMISM]: 10,
    [blockchain_name_1.BLOCKCHAIN_NAME.CRONOS]: 25,
    [blockchain_name_1.BLOCKCHAIN_NAME.OKE_X_CHAIN]: 66,
    [blockchain_name_1.BLOCKCHAIN_NAME.GNOSIS]: 100,
    [blockchain_name_1.BLOCKCHAIN_NAME.FUSE]: 122,
    [blockchain_name_1.BLOCKCHAIN_NAME.MOONBEAM]: 1284,
    [blockchain_name_1.BLOCKCHAIN_NAME.CELO]: 42220,
    [blockchain_name_1.BLOCKCHAIN_NAME.BOBA]: 288,
    [blockchain_name_1.BLOCKCHAIN_NAME.BOBA_BSC]: 56288,
    [blockchain_name_1.BLOCKCHAIN_NAME.ASTAR_EVM]: 592,
    [blockchain_name_1.BLOCKCHAIN_NAME.ETHEREUM_POW]: 10001,
    [blockchain_name_1.BLOCKCHAIN_NAME.KAVA]: 2222,
    [blockchain_name_1.BLOCKCHAIN_NAME.TRON]: 195,
    [blockchain_name_1.BLOCKCHAIN_NAME.BITGERT]: 32520,
    [blockchain_name_1.BLOCKCHAIN_NAME.OASIS]: 42262,
    [blockchain_name_1.BLOCKCHAIN_NAME.METIS]: 1088,
    [blockchain_name_1.BLOCKCHAIN_NAME.DFK]: 53935,
    [blockchain_name_1.BLOCKCHAIN_NAME.KLAYTN]: 8217,
    [blockchain_name_1.BLOCKCHAIN_NAME.VELAS]: 106,
    [blockchain_name_1.BLOCKCHAIN_NAME.SYSCOIN]: 57,
    [blockchain_name_1.BLOCKCHAIN_NAME.EOS]: 59,
    [blockchain_name_1.BLOCKCHAIN_NAME.ETHEREUM_CLASSIC]: 61,
    [blockchain_name_1.BLOCKCHAIN_NAME.FLARE]: 14,
    [blockchain_name_1.BLOCKCHAIN_NAME.IOTEX]: 4689,
    [blockchain_name_1.BLOCKCHAIN_NAME.ONTOLOGY]: 58,
    [blockchain_name_1.BLOCKCHAIN_NAME.THETA]: 361,
    [blockchain_name_1.BLOCKCHAIN_NAME.XDC]: 50,
    [blockchain_name_1.BLOCKCHAIN_NAME.BITCOIN_CASH]: 10000,
    [blockchain_name_1.BLOCKCHAIN_NAME.ZK_SYNC]: 324,
    [blockchain_name_1.BLOCKCHAIN_NAME.PULSECHAIN]: 369,
    [blockchain_name_1.BLOCKCHAIN_NAME.LINEA]: 59144,
    [blockchain_name_1.BLOCKCHAIN_NAME.BASE]: 8453,
    [blockchain_name_1.BLOCKCHAIN_NAME.MANTLE]: 5000,
    [blockchain_name_1.BLOCKCHAIN_NAME.MANTA_PACIFIC]: 169,
    [blockchain_name_1.BLOCKCHAIN_NAME.SCROLL]: 534352,
    [blockchain_name_1.BLOCKCHAIN_NAME.ZETACHAIN]: 7000,
    [blockchain_name_1.BLOCKCHAIN_NAME.BLAST]: 81457,
    // Tesnents
    [blockchain_name_1.BLOCKCHAIN_NAME.GOERLI]: 5,
    [blockchain_name_1.BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN_TESTNET]: 87,
    [blockchain_name_1.BLOCKCHAIN_NAME.MUMBAI]: 80001,
    [blockchain_name_1.BLOCKCHAIN_NAME.FUJI]: 43113,
    [blockchain_name_1.BLOCKCHAIN_NAME.SCROLL_SEPOLIA]: 534351,
    [blockchain_name_1.BLOCKCHAIN_NAME.ARTHERA]: 10243,
    [blockchain_name_1.BLOCKCHAIN_NAME.TAIKO]: 167008,
    [blockchain_name_1.BLOCKCHAIN_NAME.SEPOLIA]: 11155111,
    [blockchain_name_1.BLOCKCHAIN_NAME.BERACHAIN]: 80085,
    [blockchain_name_1.BLOCKCHAIN_NAME.BLAST_TESTNET]: 168587773,
    [blockchain_name_1.BLOCKCHAIN_NAME.HOLESKY]: 17000,
    // Non EVN blockchains
    [blockchain_name_1.BLOCKCHAIN_NAME.BITCOIN]: 5555,
    [blockchain_name_1.BLOCKCHAIN_NAME.FILECOIN]: 314,
    [blockchain_name_1.BLOCKCHAIN_NAME.SOLANA]: 7565164
};
//# sourceMappingURL=blockchain-id.js.map