export declare const CELER_TRANSFER_STATUS: {
    readonly XS_UNKNOWN: "XS_UNKNOWN";
    readonly XS_WAITING_FOR_SGN_CONFIRMATION: "XS_WAITING_FOR_SGN_CONFIRMATION";
    readonly XS_WAITING_FOR_FUND_RELEASE: "XS_WAITING_FOR_FUND_RELEASE";
    readonly XS_COMPLETED: "XS_COMPLETED";
    readonly XS_TO_BE_REFUND: "XS_TO_BE_REFUND";
    readonly XS_REFUND_TO_BE_CONFIRMED: "XS_REFUND_TO_BE_CONFIRMED";
    readonly XS_REFUNDED: "XS_REFUNDED";
};
export type CelerTransferStatus = (typeof CELER_TRANSFER_STATUS)[keyof typeof CELER_TRANSFER_STATUS];
