import { ExactInputOutputSwapMethodsList, RegularSwapMethodsList, SupportingFeeSwapMethodsList, SwapMethodsList } from "../common/uniswap-v2-abstract/constants/SWAP_METHOD";
export declare const KLAY_EXACT_INPUT_REGULAR_SWAP_METHOD: RegularSwapMethodsList;
export declare const KLAY_EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD: SupportingFeeSwapMethodsList;
export declare const KLAY_EXACT_INPUT_SWAP_METHOD: SwapMethodsList;
export declare const KLAY_EXACT_OUTPUT_REGULAR_SWAP_METHOD: RegularSwapMethodsList;
export declare const KLAY_EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD: SupportingFeeSwapMethodsList;
export declare const KLAY_EXACT_OUTPUT_SWAP_METHOD: SwapMethodsList;
export declare const KLAY_SWAP_METHOD: ExactInputOutputSwapMethodsList;
