import { ExactInputOutputSwapMethodsList, RegularSwapMethodsList, SupportingFeeSwapMethodsList, SwapMethodsList } from "../SWAP_METHOD";
export declare const ETH_EXACT_INPUT_REGULAR_SWAP_METHOD: RegularSwapMethodsList;
export declare const ETH_EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD: SupportingFeeSwapMethodsList;
export declare const ETH_EXACT_INPUT_SWAP_METHOD: SwapMethodsList;
export declare const ETH_EXACT_OUTPUT_REGULAR_SWAP_METHOD: RegularSwapMethodsList;
export declare const ETH_EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD: SupportingFeeSwapMethodsList;
export declare const ETH_EXACT_OUTPUT_SWAP_METHOD: SwapMethodsList;
export declare const ETH_SWAP_METHOD: ExactInputOutputSwapMethodsList;
